---
- name: download
  get_url: url="{{ btsync_url[ansible_architecture] }}"
           dest=/tmp/btsync.tar.gz
  register: download

- name: extract
  command: tar xvzf /tmp/btsync.tar.gz -C /tmp
  when: download | changed

- name: copy btsync to binary dir
  copy: src=/tmp/btsync dest={{ btsync_binary_dir }}/btsync state=file mode=755 owner={{ btsync_user }}
  notify: start btsync
  when: download | changed

- name: install service
  template: src=btsync dest=/etc/init.d/{{ btsync_service_name }}  mode=755
  when: ansible_service_mgr != "systemd"

- name: install systemd service
  template: src=btsync-template.service.systemd.j2 dest=/etc/systemd/system/{{ btsync_service_name }}.service mode=755
  when: ansible_service_mgr == "systemd"

- name: activate service
  service: name={{ btsync_service_name }} enabled=yes

- name: check_btsync_user
  user: name={{ btsync_user }} comment="Created by ansible btsync." shell=/bin/false 

- name: create .sync directory
  file: path=/home/{{ btsync_user }}/.sync owner={{ btsync_user }} group={{ btsync_user }} mode=0700 state=directory

- name: copy config
  template: src=config.json dest=/home/{{ btsync_user }}/.sync/ owner={{ btsync_user }} group={{ btsync_user }} mode=700
  notify: restart {{ btsync_service_name }}

- name: create folders
  file: path={{ item.path }} recurse=yes state=directory owner={{ btsync_user }} group={{ btsync_user }} mode=700
  with_items: btsync_shared_folders
  when: btsync_shared_folders is defined
