---
- name: create btsync binary directory
  file: path={{ btsync_binary_dir }} group={{ btsync_user }} owner={{ btsync_user }} mode=0700 state=directory recurse=yes
  
- name: download and install binary
  unarchive: src="{{ btsync_url[ansible_architecture] }}" 
             dest={{ btsync_binary_dir }} mode=755 owner={{ btsync_user }}
             copy=no

- name: install service
  template: src=btsync dest=/etc/init.d/{{ btsync_service_name }}  mode=755
  when: ansible_service_mgr != "systemd"

- name: install systemd service
  template: src=btsync-template.service.systemd.j2 dest=/etc/systemd/system/{{ btsync_service_name }}.service mode=755
  when: ansible_service_mgr == "systemd"

- name: systemd reload
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: activate service
  service: name={{ btsync_service_name }} enabled=yes

- name: check_btsync_user
  user: name={{ btsync_user }} comment="Created by ansible btsync." shell=/bin/false 

- name: create .sync directory
  file: path=/home/{{ btsync_user }}/.sync owner={{ btsync_user }} group={{ btsync_user }} mode=0700 state=directory

- name: copy config
  template: src=config.json.j2 dest=/home/{{ btsync_user }}/.sync/ owner={{ btsync_user }} group={{ btsync_user }} mode=700
  notify: restart {{ btsync_service_name }}

- name: create folders
  file: path={{ item.path }} recurse=yes state=directory owner={{ btsync_user }} group={{ btsync_user }} mode=700
  with_items: btsync_shared_folders
  when: btsync_shared_folders is defined
