---
- name: start btsync
  service: name={{ btsync_service_name }} state=started

- name: restart btsync
  service: name={{ btsync_service_name }} state=restarted

- name: stop btsync
  service: name={{ btsync_service_name }} state=restarted

- name: reload systemd
  command: systemctl daemon-reload
